package game.enums;

import java.awt.event.KeyEvent;

//Public enum for the keyboard keys. Use these values when checking input.
public enum Keys {
	A(KeyEvent.VK_A),
	B(KeyEvent.VK_B),
	C(KeyEvent.VK_C),
	D(KeyEvent.VK_D),
	E(KeyEvent.VK_E),
	F(KeyEvent.VK_F),
	G(KeyEvent.VK_G),
	H(KeyEvent.VK_H),
	I(KeyEvent.VK_I),
	J(KeyEvent.VK_J),
	K(KeyEvent.VK_K),
	L(KeyEvent.VK_L),
	M(KeyEvent.VK_M),
	N(KeyEvent.VK_N),
	O(KeyEvent.VK_O),
	P(KeyEvent.VK_P),
	Q(KeyEvent.VK_Q),
	R(KeyEvent.VK_R),
	S(KeyEvent.VK_S),
	T(KeyEvent.VK_T),
	U(KeyEvent.VK_U),
	V(KeyEvent.VK_V),
	W(KeyEvent.VK_W),
	X(KeyEvent.VK_X),
	Y(KeyEvent.VK_Y),
	Z(KeyEvent.VK_Z),
	
	D0(KeyEvent.VK_0),
	D1(KeyEvent.VK_1),
	D2(KeyEvent.VK_2),
	D3(KeyEvent.VK_3),
	D4(KeyEvent.VK_4),
	D5(KeyEvent.VK_5),
	D6(KeyEvent.VK_6),
	D7(KeyEvent.VK_7),
	D8(KeyEvent.VK_8),
	D9(KeyEvent.VK_9),
	
	F1(KeyEvent.VK_F1),
	F2(KeyEvent.VK_F2),
	F3(KeyEvent.VK_F3),
	F4(KeyEvent.VK_F4),
	F5(KeyEvent.VK_F5),
	F6(KeyEvent.VK_F6),
	F7(KeyEvent.VK_F7),
	F8(KeyEvent.VK_F8),
	F9(KeyEvent.VK_F9),
	F10(KeyEvent.VK_F10),
	F11(KeyEvent.VK_F11),
	F12(KeyEvent.VK_F12),
	
	Up(KeyEvent.VK_UP),
	Down(KeyEvent.VK_DOWN),
	Left(KeyEvent.VK_LEFT),
	Right(KeyEvent.VK_RIGHT),
	
	Escape(KeyEvent.VK_ESCAPE),
	Tilde(KeyEvent.VK_BACK_QUOTE),
	BackQuote(KeyEvent.VK_BACK_QUOTE),
	Tab(KeyEvent.VK_TAB),
	CapsLock(KeyEvent.VK_CAPS_LOCK),
	Shift(KeyEvent.VK_SHIFT),
	Control(KeyEvent.VK_CONTROL),
	Alt(KeyEvent.VK_ALT),
	Space(KeyEvent.VK_SPACE),
	PageUp(KeyEvent.VK_PAGE_UP),
	PageDown(KeyEvent.VK_PAGE_DOWN),
	Enter(KeyEvent.VK_ENTER),
	Comma(KeyEvent.VK_COMMA),
	Period(KeyEvent.VK_PERIOD),
	Slash(KeyEvent.VK_SLASH),
	SemiColon(KeyEvent.VK_SEMICOLON),
	Quote(KeyEvent.VK_QUOTE),
	LeftBracket(KeyEvent.VK_OPEN_BRACKET),
	RightBracket(KeyEvent.VK_CLOSE_BRACKET),
	BackSlash(KeyEvent.VK_BACK_SLASH),
	Minus(KeyEvent.VK_MINUS),
	Equals(KeyEvent.VK_EQUALS),
	Plus(KeyEvent.VK_EQUALS),
	BackSpace(KeyEvent.VK_BACK_SPACE),
	Delete(KeyEvent.VK_DELETE),
	Insert(KeyEvent.VK_INSERT);
	
	private int id;
	private Keys(int id) { this.id = id; }
	public int getValue() { return id; }
}